### PR TITLE
Improve French translations

### PR DESCRIPTION
**Pull request by RodrigueLemaire**
A part of the fr translate, feel free to continue

### CODE REVIEW

**Comment by lnjX** [comment]
Your file contains German translations, please fix that. And please use Weblate, it's easier for me and probably also for you.

**Comment by RodrigueLemaire** [comment]
ok sir, but i'm busy, you could just... merge it even if it is incomplite no? :place_of_worship:

**Comment by lnjX** [comment]
The problem is NOT that it's incomplete, the problem is that it's adding German translations and in a French translation file. And it's also replacing already translated strings with German translations.
I can't merge that!

You can see what you're changing here: https://github.com/minetest-mods/mtg_i18n/pull/3/files

image

**Comment by lnjX** [comment]
French translations was finished here:
https://github.com/minetest-mods/mtg_i18n/commit/a9bcef2a33af8cbff01cbadc3689868e23db2941
https://github.com/minetest-mods/mtg_i18n/pull/5

**Pull request closed without merging**
