### PR TITLE
Update for Minetes Game v0.4.17-dev

### PR DESCRIPTION
**Pull request by ghost**
Using Intllib's tools.

@LNJ2 @MuhdNurHidayat

### CODE REVIEW

**Comment by lnjX** [comment]
You'll also need to modify/update the init.lua file, otherwise the new items won't be added.

**Comment by ghost** [comment]
I believe that the nodes mentioned by @MuhdNurHidayat belong to 0.5-dev, this update is for 0.4.17-dev

**Comment by lnjX** [comment]
I'd like to continuing to use the 0.5-dev branch as said in the README. And please also update the README.

**Comment by ghost** [comment]
Sorry, I didn't noticed the change to the new Minetest version.

**Pull request closed without merging**
